default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: 172.28.128.5
  username: root
  password: s8ajaStE
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: oauth_development

test:
  <<: *default
  database: oauth_test

production:
  <<: *default
  database: oauth_production
